<?php

namespace AppBundle\Repository;

/**
 * ComandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComandaRepository extends \Doctrine\ORM\EntityRepository
{
}
