root:
    path: '/'
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /comanda
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
